### ISSUE TITLE
InsecureRequestWarning

### ISSUE THREAD

**Issue by Tecnico1931** [sheagcraig/python-jss#23]
/Library/Python/2.7/site-packages/python_jss-0.5.3-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by sheagcraig** [comment]
Assuming this is good now.
