### ISSUE TITLE
Remove pyObjc and Foundation Dependecies

### ISSUE THREAD

**Issue by mattzago** [sheagcraig/python-jss#36]
The project is great, but I'm curious how herculean the work would be to remove pyObjc/Foundation dependencies to allow python-jss to be used on other platforms (Linux mainly).

**Comment by sheagcraig** [comment]
I've never tried it on anything other than MacOS, but it only imports FoundationPlist if it's on a Mac.

The only other dependencies I see are for plutil, which it tries to use to convert binary plists (which shouldn't exist on non-Mac) and possibly the mount command not having afp support. There's another OS-dependent clause about whether to use diskutil or umount to unmount as well, but again, that should do the right thing on Linux.

Have you tried it? Where are you hitting snags? I always intended it to work on other platforms, but I haven't had that much time to test it.

**Comment by sheagcraig** [comment]
@mattzago 
I recently replaced my desk iMac with a Fedora box and have python-jss passing the (albeit limited) tests.

All of the pyObjc/Foundation framework stuff is handled appropriately by plistlib and the afp/smb mounting of distribution points works via fuse-afp and cifs-utils. Please let me know if you find it to be failing in any way on Linux!
