### ISSUE TITLE
AFP mount no longer working in version 1.0.0

### ISSUE THREAD

**Issue by galenrichards** [sheagcraig/python-jss#38]
The new code throws an "Unsupported OS" error when it tries to mount my AFP share. It's being triggered at line 671 of distribution_points.py. I'm able to mount the AFP share by hand without any issues. Also, I'm running the 0.5.9 code on another system and it is able to mount the same share.

I should mention, python-jss is being called from the latest version of AutoPkgr.

**Comment by sheagcraig** [comment]
I'm looking at it, and that's a pretty dumb logic error there.

If you look at line 671, it triggers the OS message if you're not running Linux, or not running OS X *with-the-no-browse* option set.

I'll fix that asap.

Thanks for letting me know!

**Comment by sheagcraig** [comment]
All set.

**Comment by galenrichards** [comment]
Thanks, it works great now!
