### ISSUE TITLE
LocalRepository: share_name mandatory but unused

### ISSUE THREAD

**Issue by ftiff** [sheagcraig/python-jss#45]
Class LocalRepository requires attributes {"mount_point", "share_name"}, while only mount_point seems to be needed.

Make sure to update README.md if you change this :-)

SOURCE: https://github.com/sheagcraig/python-jss/blob/3e44c7ed1d4b3a656f5aede6088921c24c1ce730/jss/distribution_point.py#L213

**Comment by sheagcraig** [comment]
I think the share_name is just used for output and repr reasons. It's not _necessary_, but it makes it more consistent with the other Repository types, and will stay in.
