### ISSUE TITLE
saving new ComputerGroup object fails, b/c .jss is a str

### ISSUE THREAD

**Issue by leungjunman** [sheagcraig/python-jss#47]
When doing a .save() on a new ComputerGroup object, it throws an error that 

str does not have a method called post()

It seems like something with the inheritance isn't working correctly.   Doing a dir(new_group.jss), compared with a dir(existing_group.jss) yields very very different methods/properties.

new_group.jss is a str object, rather than what it should be.

**Comment by sheagcraig** [comment]
Can you hit me with a code example?

Looking at JSSObject.__init__ and its subsequent call of _new I don't see anything that stands out.

**Comment by leungjunman** [comment]
Here's an example.  Very simple, and please correct me if i'm creating the ComputerGroup wrong.

```
session=jss.JSS(prefs)

# create new group
group=jss.ComputerGroup("","Test Group")
group.is_smart=False
group.save()
```

It throws:
```
>>> group.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/jss/jssobject.py", line 338, in save
    updated_data = self.jss.post(self.__class__, url, self)
AttributeError: 'str' object has no attribute 'post'
```

For some reason self.jss is a 'str' and that's causing an issue.  The inheritance should have taken care of all that, but for some reason it's not, and i'm not so proficient in python to understand why ... yet :)

I can workaround this problem by getting another object that already exists, and doing something like this:

```

existing_group=session.ComputerGroup("Existing Group")
group.jss=existing_group.jss

```
and then i do 

`group.save()`

and it works ...

Thanks for this awesome library, it's been a great help.

**Comment by leungjunman** [comment]
Know what, I think i know what i was missing.  I should have put in "session" when i create the new group. I think that may be the cause of it making .jss into a blank str.  Sorry!!

**Comment by sheagcraig** [comment]
Yep-based on your code example, you're missing the first argument to the ComputerGroup class constructor, which is a JSS object (in your example, named `session`).
