### ISSUE TITLE
kNAUIOptionNoUI Error on High Sierra macOS

### ISSUE THREAD

**Issue by pauldalewilliams** [sheagcraig/python-jss#62]
https://github.com/sheagcraig/python-jss/blob/e1982466bd7e971f27525cbc31024590a456df66/jss/contrib/mount_shares_better.py#L54
https://github.com/sheagcraig/python-jss/blob/e1982466bd7e971f27525cbc31024590a456df66/jss/contrib/mount_shares_better.py#L80

These two lines are throwing an error in macOS High Sierra.  My file system is APFS (encrypted).

I'm not sure how to proceed with troubleshooting (still learning), but my guess is that something has changed with the API calls that @pudquick discussed here:  https://michaellynn.github.io/2015/08/08/learn-you-a-better-pyobjc-bridgesupport-signature/

**Comment by sheagcraig** [comment]
You are correct @pauldalewilliams. I fixed this in the testing branch in the last couple of days, and I'm just waiting to release so that it can coincide with JSSImporter so I don't mess the largest group of  consumers of python-jss up!

**Comment by pauldalewilliams** [comment]
Thanks for your great work, @sheagcraig!

**Comment by rickwhois** [comment]
Thanks for the update! Much appreciated @sheagcraig
